import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models

class Migration(migrations.Migration):
    initial = True
    dependencies = [migrations.swappable_dependency(settings.AUTH_USER_MODEL)]
    operations = [
        migrations.CreateModel(name="Cliente", fields=[("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")), ("criado_em", models.DateTimeField(auto_now_add=True)), ("atualizado_em", models.DateTimeField(auto_now=True)), ("nome", models.CharField(max_length=150, verbose_name="nome / razão social")), ("documento", models.CharField(blank=True, max_length=18, verbose_name="CPF/CNPJ")), ("telefone", models.CharField(max_length=20)), ("email", models.EmailField(blank=True, max_length=254)), ("endereco", models.CharField(max_length=255)), ("observacoes", models.TextField(blank=True))], options={"ordering": ["nome"]}),
        migrations.CreateModel(name="OrdemServico", fields=[("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")), ("criado_em", models.DateTimeField(auto_now_add=True)), ("atualizado_em", models.DateTimeField(auto_now=True)), ("numero", models.PositiveIntegerField(editable=False, unique=True)), ("tipo", models.CharField(choices=[("INSTALACAO", "Instalação fibra"), ("MANUTENCAO", "Manutenção"), ("REDE", "Rede / pontos"), ("VISITA", "Visita técnica")], max_length=15)), ("status", models.CharField(choices=[("ABERTA", "Aberta"), ("AGENDADA", "Agendada"), ("EM_ANDAMENTO", "Em andamento"), ("CONCLUIDA", "Concluída"), ("CANCELADA", "Cancelada")], default="ABERTA", max_length=15)), ("agendamento", models.DateTimeField(blank=True, null=True)), ("descricao", models.TextField()), ("solucao", models.TextField(blank=True)), ("valor", models.DecimalField(decimal_places=2, default=0, max_digits=12)), ("cliente", models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name="ordens", to="core.cliente")), ("tecnico", models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name="ordens_tecnicas", to=settings.AUTH_USER_MODEL))], options={"ordering": ["-criado_em"]}),
        migrations.CreateModel(name="Orcamento", fields=[("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")), ("criado_em", models.DateTimeField(auto_now_add=True)), ("atualizado_em", models.DateTimeField(auto_now=True)), ("numero", models.PositiveIntegerField(editable=False, unique=True)), ("descricao", models.TextField()), ("valor", models.DecimalField(decimal_places=2, max_digits=12)), ("validade", models.DateField()), ("status", models.CharField(choices=[("RASCUNHO", "Rascunho"), ("ENVIADO", "Enviado"), ("APROVADO", "Aprovado"), ("RECUSADO", "Recusado")], default="RASCUNHO", max_length=10)), ("cliente", models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name="orcamentos", to="core.cliente")), ("responsavel", models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL))], options={"ordering": ["-criado_em"]}),
        migrations.CreateModel(name="Lancamento", fields=[("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")), ("criado_em", models.DateTimeField(auto_now_add=True)), ("atualizado_em", models.DateTimeField(auto_now=True)), ("data", models.DateField(default=django.utils.timezone.localdate)), ("descricao", models.CharField(max_length=200)), ("tipo", models.CharField(choices=[("ENTRADA", "Entrada"), ("SAIDA", "Saída")], max_length=7)), ("categoria", models.CharField(max_length=80)), ("valor", models.DecimalField(decimal_places=2, max_digits=12)), ("ordem_servico", models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name="lancamentos", to="core.ordemservico"))], options={"ordering": ["-data", "-criado_em"]}),
    ]
