# Generated by Django 5.2.16 on 2026-08-02 17:24

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0009_ordemservico_nome_cliente_instalado'),
    ]

    operations = [
        migrations.CreateModel(
            name='TipoServico',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100, unique=True, verbose_name='Nome')),
                ('ativo', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'Tipo de Serviço',
                'verbose_name_plural': 'Tipos de Serviço',
                'ordering': ['nome'],
            },
        ),
        migrations.AlterField(
            model_name='ordemservico',
            name='tipo',
            field=models.CharField(blank=True, max_length=15, null=True),
        ),
        migrations.AddField(
            model_name='ordemservico',
            name='tipo_servico',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='core.tiposervico', verbose_name='Tipo de Serviço'),
        ),
    ]
