# Generated by Django 5.2.16 on 2026-08-02 17:24

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0010_tiposervico_alter_ordemservico_tipo_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ordemservico',
            name='tipo_servico',
        ),
        migrations.AlterField(
            model_name='ordemservico',
            name='tipo',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='core.tiposervico', verbose_name='Tipo de Serviço'),
        ),
    ]
