# Generated by Django 5.2.16 on 2026-08-02 18:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0012_lancamento_tecnico'),
    ]

    operations = [
        migrations.AddField(
            model_name='ordemservico',
            name='finalizado_em',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='ordemservico',
            name='iniciado_em',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
