# Generated by Django 5.2.16 on 2026-08-02 18:38

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0013_ordemservico_finalizado_em_ordemservico_iniciado_em'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Produto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('atualizado_em', models.DateTimeField(auto_now=True)),
                ('nome', models.CharField(max_length=150, unique=True)),
                ('unidade', models.CharField(default='UN', max_length=20, verbose_name='Unidade de medida')),
                ('estoque_base', models.IntegerField(default=0, verbose_name='Estoque na Sede')),
            ],
            options={
                'ordering': ['nome'],
            },
        ),
        migrations.CreateModel(
            name='ProdutoOS',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantidade', models.IntegerField()),
                ('registrado_em', models.DateTimeField(auto_now_add=True)),
                ('ordem_servico', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='materiais_utilizados', to='core.ordemservico')),
                ('produto', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='core.produto')),
            ],
            options={
                'ordering': ['registrado_em'],
            },
        ),
        migrations.CreateModel(
            name='EstoqueTecnico',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('atualizado_em', models.DateTimeField(auto_now=True)),
                ('quantidade', models.IntegerField(default=0)),
                ('tecnico', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='estoque', to=settings.AUTH_USER_MODEL)),
                ('produto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.produto')),
            ],
            options={
                'ordering': ['tecnico__username', 'produto__nome'],
                'unique_together': {('tecnico', 'produto')},
            },
        ),
    ]
