# Generated by Django 5.2.17 on 2026-08-09 03:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0017_orcamento_desconto_alter_orcamento_valor_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='tiposervico',
            name='valor_padrao',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10, verbose_name='Valor Padrão'),
        ),
        migrations.AlterField(
            model_name='tiposervico',
            name='ativo',
            field=models.BooleanField(default=True, verbose_name='Ativo'),
        ),
    ]
