# Generated by Django 5.2.17 on 2026-09-02 16:16

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0021_cliente_usuario'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ordemservico',
            name='tipo',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.tiposervico', verbose_name='Tipo de Serviço Principal'),
        ),
        migrations.CreateModel(
            name='ItemOS',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descricao', models.CharField(max_length=255)),
                ('quantidade', models.PositiveIntegerField(default=1)),
                ('valor_unitario', models.DecimalField(decimal_places=2, default=0.0, max_digits=12)),
                ('ordem_servico', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='itens', to='core.ordemservico')),
            ],
        ),
    ]
