# Generated by Django 5.2.17 on 2026-09-02 16:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0022_alter_ordemservico_tipo_itemos'),
    ]

    operations = [
        migrations.AddField(
            model_name='ordemservico',
            name='plus_code',
            field=models.CharField(blank=True, help_text='Ex: 87G8Q222+22', max_length=50, verbose_name='Plus Code (Localização)'),
        ),
    ]
