# Generated by Django 5.2.17 on 2026-09-02 16:29

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0023_ordemservico_plus_code'),
    ]

    operations = [
        migrations.AddField(
            model_name='orcamento',
            name='cliente_final',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='orcamentos', to='core.clientefinal'),
        ),
    ]
