# Generated by Django 5.2.17 on 2026-09-09 01:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0024_orcamento_cliente_final'),
    ]

    operations = [
        migrations.AddField(
            model_name='produto',
            name='preco_base',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=12, verbose_name='Preço Base'),
        ),
    ]
