# Generated by Django 5.2.17 on 2026-09-11 00:35

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Banco',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100, verbose_name='Nome do Banco')),
                ('saldo_atual', models.DecimalField(decimal_places=2, default=0.0, max_digits=12, verbose_name='Saldo Atual')),
                ('limite_cheque_especial', models.DecimalField(decimal_places=2, default=0.0, max_digits=12, verbose_name='Limite Cheque Especial')),
                ('limite_credito', models.DecimalField(decimal_places=2, default=0.0, max_digits=12, verbose_name='Limite de Crédito')),
            ],
        ),
        migrations.CreateModel(
            name='Categoria',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100)),
                ('tipo', models.CharField(choices=[('ENTRADA', 'Entrada'), ('SAIDA', 'Saída'), ('AMBOS', 'Ambos')], default='AMBOS', max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='Divida',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descricao', models.CharField(max_length=255, verbose_name='Descrição da Dívida')),
                ('valor', models.DecimalField(decimal_places=2, max_digits=12)),
                ('data_vencimento', models.DateField()),
                ('status', models.CharField(choices=[('PENDENTE', 'Pendente'), ('PAGO', 'Pago')], default='PENDENTE', max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='Emprestimo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome_pessoa', models.CharField(max_length=150, verbose_name='Amigo/Familiar')),
                ('valor', models.DecimalField(decimal_places=2, max_digits=12)),
                ('data_emprestimo', models.DateField(default=django.utils.timezone.now)),
                ('data_devolucao', models.DateField(verbose_name='Data de Devolução Prometida')),
                ('status', models.CharField(choices=[('PENDENTE', 'Pendente'), ('PAGO', 'Pago/Devolvido')], default='PENDENTE', max_length=10)),
                ('observacao', models.TextField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='VendaParcelada',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cliente', models.CharField(max_length=200)),
                ('descricao', models.TextField(verbose_name='Descrição da Venda')),
                ('valor_total', models.DecimalField(decimal_places=2, max_digits=12)),
                ('quantidade_parcelas', models.PositiveIntegerField()),
                ('data_venda', models.DateField(default=django.utils.timezone.now)),
            ],
        ),
        migrations.CreateModel(
            name='Transacao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(choices=[('ENTRADA', 'Entrada'), ('SAIDA', 'Saída')], max_length=10)),
                ('valor', models.DecimalField(decimal_places=2, max_digits=12)),
                ('descricao', models.CharField(max_length=255, verbose_name='Descrição')),
                ('data', models.DateField(default=django.utils.timezone.now)),
                ('status', models.CharField(choices=[('PENDENTE', 'Pendente'), ('PAGO', 'Pago')], default='PAGO', max_length=10)),
                ('banco', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='transacoes', to='teddyfinanca.banco')),
                ('categoria', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='teddyfinanca.categoria')),
                ('divida_origem', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='teddyfinanca.divida')),
                ('emprestimo_origem', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='teddyfinanca.emprestimo')),
                ('venda_origem', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='teddyfinanca.vendaparcelada')),
            ],
        ),
    ]
