# Generated by Django 5.2.17 on 2026-09-11 01:49

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('teddyfinanca', '0002_alter_categoria_options_alter_divida_options_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='vendaparcelada',
            name='entrada',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=12, verbose_name='Valor de Entrada'),
        ),
        migrations.CreateModel(
            name='ParcelaVenda',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero', models.PositiveIntegerField()),
                ('valor', models.DecimalField(decimal_places=2, max_digits=12)),
                ('data_vencimento', models.DateField()),
                ('status', models.CharField(choices=[('PENDENTE', 'Pendente'), ('PAGO', 'Pago')], default='PENDENTE', max_length=10)),
                ('usuario', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('venda', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='parcelas', to='teddyfinanca.vendaparcelada')),
            ],
            options={
                'ordering': ['data_vencimento'],
            },
        ),
    ]
