# Generated by Django 5.2.17 on 2026-09-11 01:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('teddyfinanca', '0003_vendaparcelada_entrada_parcelavenda'),
    ]

    operations = [
        migrations.AddField(
            model_name='divida',
            name='arquivado',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='emprestimo',
            name='arquivado',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='vendaparcelada',
            name='arquivado',
            field=models.BooleanField(default=False),
        ),
    ]
