# Generated by Django 5.2.17 on 2026-09-11 02:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('teddyfinanca', '0004_divida_arquivado_emprestimo_arquivado_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='divida',
            name='valor_pago',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=12),
        ),
        migrations.AddField(
            model_name='emprestimo',
            name='valor_pago',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=12),
        ),
        migrations.AddField(
            model_name='parcelavenda',
            name='valor_pago',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=12),
        ),
    ]
