# Generated by Django 5.2.17 on 2026-09-11 02:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('teddyfinanca', '0005_divida_valor_pago_emprestimo_valor_pago_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='divida',
            name='tipo_recorrencia',
            field=models.CharField(choices=[('UNICA', 'Única'), ('RECORRENTE', 'Fixa Mensal (Recorrente)')], default='UNICA', max_length=15),
        ),
    ]
