# Generated by Django 5.2.17 on 2026-09-12 00:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('teddyfinanca', '0007_assinatura'),
    ]

    operations = [
        migrations.AddField(
            model_name='transacao',
            name='forma_pagamento',
            field=models.CharField(choices=[('DEBITO', 'Conta/Débito'), ('CREDITO', 'Cartão de Crédito')], default='DEBITO', max_length=10),
        ),
    ]
