# Generated by Django 5.2.17 on 2026-09-12 01:06

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('teddyfinanca', '0008_transacao_forma_pagamento'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CompraParcelada',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descricao', models.CharField(max_length=255, verbose_name='Descrição da Compra')),
                ('valor_total', models.DecimalField(decimal_places=2, max_digits=12)),
                ('entrada', models.DecimalField(decimal_places=2, default=0.0, max_digits=12)),
                ('quantidade_parcelas', models.PositiveIntegerField()),
                ('data_compra', models.DateField(default=django.utils.timezone.now)),
                ('arquivado', models.BooleanField(default=False)),
                ('usuario', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Compra Parcelada',
                'verbose_name_plural': 'Compras Parceladas',
            },
        ),
        migrations.AddField(
            model_name='divida',
            name='compra_vinculada',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='parcelas', to='teddyfinanca.compraparcelada'),
        ),
    ]
