# Generated by Django 5.2.17 on 2026-09-12 01:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('teddyfinanca', '0009_compraparcelada_divida_compra_vinculada'),
    ]

    operations = [
        migrations.AddField(
            model_name='compraparcelada',
            name='observacao',
            field=models.TextField(blank=True, null=True, verbose_name='Descrição (Opcional)'),
        ),
        migrations.AddField(
            model_name='divida',
            name='observacao',
            field=models.TextField(blank=True, null=True, verbose_name='Descrição (Opcional)'),
        ),
        migrations.AlterField(
            model_name='compraparcelada',
            name='descricao',
            field=models.CharField(max_length=255, verbose_name='Nome da Compra'),
        ),
        migrations.AlterField(
            model_name='divida',
            name='descricao',
            field=models.CharField(max_length=255, verbose_name='Nome da Dívida'),
        ),
    ]
