# Generated by Django 5.2.17 on 2026-09-13 19:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('teddyfinanca', '0010_compraparcelada_observacao_divida_observacao_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='banco',
            name='pluggy_account_id',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='ID Conta Pluggy (Account)'),
        ),
        migrations.AddField(
            model_name='banco',
            name='pluggy_item_id',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='ID Conexão Pluggy (Item)'),
        ),
        migrations.AddField(
            model_name='transacao',
            name='pluggy_transaction_id',
            field=models.CharField(blank=True, max_length=255, null=True, unique=True, verbose_name='ID Transação Pluggy'),
        ),
    ]
