# Generated by Django 6.1.1 on 2026-09-14 02:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('teddyfinanca', '0012_perfil'),
    ]

    operations = [
        migrations.AddField(
            model_name='emprestimo',
            name='telefone_contato',
            field=models.CharField(blank=True, max_length=25, null=True, verbose_name='WhatsApp do Contato'),
        ),
        migrations.AddField(
            model_name='vendaparcelada',
            name='telefone_cliente',
            field=models.CharField(blank=True, max_length=25, null=True, verbose_name='WhatsApp do Cliente'),
        ),
    ]
