# Generated by Django 5.2.17 on 2026-09-15 03:13

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('teddyfinanca', '0013_emprestimo_telefone_contato_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Venda',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cliente', models.CharField(max_length=200)),
                ('descricao', models.TextField(verbose_name='Descrição da Venda')),
                ('valor', models.DecimalField(decimal_places=2, max_digits=12)),
                ('data_venda', models.DateField(default=django.utils.timezone.now)),
                ('arquivado', models.BooleanField(default=False)),
                ('banco', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='teddyfinanca.banco', verbose_name='Receber em qual Banco?')),
                ('usuario', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Venda à Vista',
                'verbose_name_plural': 'Vendas à Vista',
            },
        ),
    ]
