# Generated by Django 5.2.17 on 2026-09-15 23:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('teddyfinanca', '0015_jogovelha_presencaonline'),
    ]

    operations = [
        migrations.AddField(
            model_name='presencaonline',
            name='derrotas',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='presencaonline',
            name='vitorias',
            field=models.IntegerField(default=0),
        ),
    ]
