# Generated by Django 5.2.17 on 2026-09-19 01:16

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('teddyfinanca', '0017_chatglobal_chatprivado'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='venda',
            options={'verbose_name': 'Venda', 'verbose_name_plural': 'Vendas'},
        ),
        migrations.AddField(
            model_name='venda',
            name='data_vencimento',
            field=models.DateField(default=django.utils.timezone.now, verbose_name='Data para Receber'),
        ),
        migrations.AddField(
            model_name='venda',
            name='status',
            field=models.CharField(choices=[('PENDENTE', 'Pendente'), ('PAGO', 'Pago')], default='PENDENTE', max_length=10),
        ),
        migrations.AddField(
            model_name='venda',
            name='valor_pago',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=12),
        ),
        migrations.AlterField(
            model_name='venda',
            name='data_venda',
            field=models.DateField(default=django.utils.timezone.now, verbose_name='Data da Venda'),
        ),
    ]
