# Generated by Django 5.2.17 on 2026-09-19 02:02

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('teddyfinanca', '0018_alter_venda_options_venda_data_vencimento_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='vendaparcelada',
            name='primeiro_vencimento',
            field=models.DateField(default=django.utils.timezone.now, verbose_name='Vencimento da 1ª Parcela'),
        ),
    ]
