# Generated by Django 5.2.17 on 2026-09-19 02:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('teddyfinanca', '0019_vendaparcelada_primeiro_vencimento'),
    ]

    operations = [
        migrations.AddField(
            model_name='emprestimo',
            name='quantidade_parcelas',
            field=models.PositiveIntegerField(default=1, verbose_name='Qtd. Parcelas'),
        ),
        migrations.AlterField(
            model_name='emprestimo',
            name='data_devolucao',
            field=models.DateField(verbose_name='Data de Devolução Prometida / 1º Vencimento'),
        ),
    ]
