# Generated by Django 5.2.17 on 2026-09-19 03:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('teddyfinanca', '0020_emprestimo_quantidade_parcelas_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='divida',
            name='data_pagamento',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='emprestimo',
            name='data_pagamento',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='parcelavenda',
            name='data_pagamento',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='venda',
            name='data_pagamento',
            field=models.DateField(blank=True, null=True),
        ),
    ]
